import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Menu from "../components/Menu";
import Footer from "../components/Footer";
import { useEffect, useRef } from "react";
import { GetStaticProps } from "next";
import Reservation from "@/components/Reservation";
import Delivery from "@/components/Delivery";
import CookieConsent from "@/components/CookieConsent";


export default function Home ({ locale }: { locale: string }) {
  
  console.log("locale", locale)

  const menuRef = useRef<null | HTMLDivElement>(null)
  const executeScroll = () =>
    menuRef?.current &&
    menuRef.current.scrollIntoView({
      block: "center",
      behavior: "smooth",
    })

  useEffect(() => {
    executeScroll()
  }, [])

  return (
    <>
      <Head>
        <title>Lias Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* theme colour for the browser bar: */}
        <meta name="theme-color" content="#4285f4"></meta>
      </Head>
      <main className={styles.main}>
        <div className={styles.noiseTexture}>
          <Navbar />
          <Header />
          <div className="mt-52 absolute" ref={menuRef} />
          <Menu />
          <Delivery />
          <Reservation />
          <Footer />
        </div>

        <div className={styles.containerBackToTopButton}>
          <a className={styles.backToTopButton} href="#" />
        </div>

        <CookieConsent />
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  console.log(locale)
  return {
    props: {
      locale,
    },
  }
}
