import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Menu from '../components/Menu'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Lias Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* theme colour for the browser bar: */}
        <meta name="theme-color" content="#4285f4"></meta>
      </Head>
      <main className={styles.main}>
        <div className={styles.noiseTexture}>
          <Navbar />
          <Header />
          <Menu />
          <Footer />
        </div>

        <div className={styles.containerBackToTopButton}>
          <a className={styles.backToTopButton} href='#' />
        </div>  
      </main>
    </>
  )
}
